# .fitdock.yml is lightweight method to ensure that FIT servers are configured
# properly to support docker-compose apps. At present it only supports a few
# simple configuration items. Additional features may be added in the future.

# Specify required "fitdock" version
# Ultimately need to specify version here, but for now use the default
# `fitdock` branch
# fitdock_version: tags/1.0.0

# Where to install the docker-compose app
install_dir: /opt/coda

# What directories need to be configured on the host, and what permissions/
# ownership to give them. Primary use for this is to configure directories
# that will be used in docker-compose.yml as volume mounts.
directories:
  - path: /d1/coda/static
    mode: "0775"
    owner: gitlab-runner
    group: gitlab-runner
  - path: /d1/coda/postgres
    mode: "0775"
    owner: gitlab-runner
    group: gitlab-runner
  - path: /d1/coda/db-init
    mode: "0775"
    owner: gitlab-runner
    group: gitlab-runner
  - path: /d1/coda/redis
    mode: "0775"
    owner: gitlab-runner
    group: gitlab-runner

# Ensure SSL key/cert exist at the specified locations. If they do not exist,
# a self-signed cert will be generated. This SSL is NOT the user-facing SSL
# cert; it is only for encrypting traffic between the VM running this app and
# the FIT proxy/load-balancer. The FIT proxy will accept self-signed certs,
# but the FIT sysadmins should switch this self-signed cert out with a valid
# cert.
use_ssl:
  key: /etc/pki/tls/private/nginx.key
  cert: /etc/pki/tls/certs/nginx.crt
