# README
# This defines the pipeline of jobs that runs when you push to gitlab
# To check the validity of this file, try the live editor:
# https://gitlab.fit.nasa.gov/coda/coda/-/ci/lint

# Use EMSS' version of node:18-alpine
image: "$CI_REGISTRY/emss/docker-images:node-18-alpine"

default:
  artifacts:
    # Aggressively expire artifacts. The latest for any branch never expires
    expire_in: 1 day
  timeout: 10 minutes

variables:
  HOME: "/tmp" # required for openshift for now
  a11y_urls: "https://coda-int.fit.nasa.gov/view?date=2021-03-13&gmt=14:49:46&v=2.0&l=n&s=0&f1=01001iss064m010721435&f2=01011iss064m020721435&f3=0300&f4=0701&f5=051&f6=04&f7=080"

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .next/cache/

# also run standard FIT dependency and package checks
# https://gitlab.fit.nasa.gov/developer-ecosystem/ci-job-templates
include:
  - project: "developer-ecosystem/ci-job-templates"
    ref: 3.3.0
    file: "/rollups/all-projects.gitlab-ci.yml"
  - template: "Verify/Accessibility.gitlab-ci.yml"

  # Docker-in-Docker template for building docker images using docker runners
  - project: "developer-ecosystem/ci-job-templates"
    ref: 101-update-dind-extend-to-docker-20
    file: "/extends/dind.gitlab-ci.yml"

stages:
  - stageless

# Overrride some properties on FIT jobs. Unfortunately using a template for these
# make GitLab angry, so a lot of repetition
project-check:
  stage: stageless
  needs: []
  tags: ["openshift"]
eslint-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
nodejs-scan-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
semgrep-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
secret_detection:
  stage: stageless
  needs: []
  tags: ["openshift"]
code-count:
  stage: stageless
  needs: []
  tags: ["openshift"]
a11y:
  stage: stageless

# manually overwrite the dependency-check to add our own suppression.xml
dependency-check:
  stage: stageless
  needs: ["install_dependencies"] # dependency-check takes a while, don't wait for "test" job
  tags: ["docker", "linux"] # can't use openshift yet
  image:
    # Specify the Docker image to be used for the job, which is a customized image for running OWASP
    # dependency-check in a GitLab CI job
    name: $CI_REGISTRY/developer-ecosystem/dependency-check:latest
    # Entrypoint is overridden to allow a script to be run
    entrypoint: [""]
  script:
    # Run dependency-check from the location installed in the Docker container with the following arguments:
    # --scan "./"                                         Scans all files and folders within the working folder,
    #                                                     which contains the repository files as well as any
    #                                                     artifacts from prior jobs in the pipeline
    # --format ALL                                        Saves output in all formats so that HTML and JSON
    #                                                     files are available
    # --project "$CI_PROJECT_NAME"                        Use the GitLab project name, which is included in
    #                                                     the report
    # --failOnCVSS 0                                      Forces job to fail if any vulnerabilities are found
    # --suppression /suppressions/fp-cpe-suppression.xml  Suppress false positives where the dependency is
    #                                                     improperly identified
    # --suppression /suppressions/fp-cve-suppression.xml  Suppress false positives where the dependency is
    #                                                     properly identified, but the  CVE is a false positive
    - /usr/share/dependency-check/bin/dependency-check.sh --scan "./" --format ALL --project "$CI_PROJECT_NAME" --failOnCVSS 0 --suppression /suppressions/fp-cpe-suppression.xml --suppression /suppressions/fp-cve-suppression.xml --suppression ./ci/suppression.xml
  # Allow failure will report a failure, but continue execution of the pipeline
  allow_failure: true
  artifacts:
    # Saving artifacts always forces them to be saved on failure as well as success
    when: always
    # Save the HTML and JSON formatted results as artifacts
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"

npm-audit:
  stage: stageless
  needs: []
  tags: ["openshift"]
  allow_failure: true
  script:
    - npm audit --json > npm-audit-report.json && echo "No vulnerabilities found" || npm audit
  artifacts:
    # Saving artifacts always forces them to be saved on failure as well as success
    when: always
    # Save the JSON formatted results as an artifact
    paths:
      - "./npm-audit-report.json"

install_dependencies:
  stage: stageless

  # This could be openshift, but it runs faster in a VM; other jobs rely on it, so get it done ASAP
  tags: ["docker", "linux"]
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - ./node_modules/*

#
# Creates Software Bill of Materials
#
node-sbom:
  stage: stageless
  allow_failure: true
  tags: ["docker", "linux"] # Can't be openshift due to it not pulling latest tag
  needs: ["install_dependencies"]
  image: $CI_REGISTRY/emss/docker-images:node-ci-sbom
  script:
    - /create-and-compare-bom.sh ./BOM.md
  artifacts:
    when: always
    paths:
      - "./bom.json"
      - "./new-bom.md"

.make-dotenv:
  image: "$CI_REGISTRY/emss/docker-images:envsubst-bash-in-envsubst"
  stage: stageless
  needs: []
  tags: ["openshift"]
  before_script:
    - mkdir -p ./.local
    - echo "${DOTENV_SECRET}" > ./.env.secret

    # make-dotenv.sh should detect the script directory to read .env.template and write .env
    # relatively, but Alpine Linux uses standard POSIX sh, not Bash, which cannot do this [1]. So
    # we need to `cd` into the ./scripts directory first when using Alpine.
    #
    # Ref: [1] https://stackoverflow.com/a/49794678/2782380
    - cd ./scripts

    - >
      if [ "${CI_COMMIT_REF_SLUG}" == "prod" ]; then
        IMAGE_VERSION="prod"
      elif [ "${CI_COMMIT_REF_SLUG}" == "int" ]; then
        IMAGE_VERSION="int"
      else
        IMAGE_VERSION="dev"
      fi

    - export IMAGE_VERSION

make-test-dotenv:
  extends: .make-dotenv
  script:
    - bash ./make-dotenv.sh test
  artifacts:
    paths:
      - .env

make-fit-dotenv:
  extends: .make-dotenv
  script:
    - bash ./make-dotenv.sh fit
  artifacts:
    paths:
      - .env
      # Also export these for easy use by deployer
      - .fitdock.yml
      - docker-compose.yml

test:
  stage: stageless
  needs:
    - install_dependencies
    - make-test-dotenv
  tags: ["openshift"]
  script:
    - npm run lint
    - npm run tsc
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/cobertura-coverage.xml
      junit:
        - junit.xml
    paths:
      - ./coverage/*

# test against next version of node that CODA may use, but allow to fail
test-node-next:
  stage: stageless
  image: "$CI_REGISTRY/emss/docker-images:node-16-alpine"
  needs:
    - install_dependencies
    - make-test-dotenv
  tags: ["openshift"]
  allow_failure: true
  script:
    - npm run lint
    - npm run tsc
    - npm t

build:
  stage: stageless
  needs:
    - install_dependencies
    - make-fit-dotenv

  # Use deploy image to be `root` rather than other emss/docker-image images which set user to node
  # to run in OpenShift. But next.js requires touching some other directories that require more
  # permissions, so rather than configuring those for now just run as root. Also set home to /root
  # since default is /tmp to work with OpenShift
  #
  # We're using Node 16 here just because there isn't a deploy-node-18-alpine yet in
  # emss/docker-images. Could add one easily enough.
  variables:
    HOME: /root
  image: "$CI_REGISTRY/emss/docker-images:deploy-node-16-alpine"

  # Could be openshift, but it runs faster in a VM; Since it's the longest-running job, run in VM
  tags: ["docker", "linux"]
  script:
    - npm run build
  artifacts:
    paths:
      - .next
      - dist

.docker-compose-build-template:
  stage: stageless
  needs:
    - make-fit-dotenv
  extends: .dind
  script:
    # required for nextjs to have NASA CA cert
    - echo "${ENV_LOCAL_CERT_PEM}" > ./.env.local.cert.pem

    # Get IMAGE_VERSION from .env
    - source .env

    - docker-compose -f docker-compose.yml -f docker-compose.preview.yml build --no-cache ${SERVICE_NAME}
    - TEMP_IMAGE_NAME="${CI_REGISTRY_IMAGE}/${SERVICE_NAME}:preview-${IMAGE_VERSION}"
    - docker push "${TEMP_IMAGE_NAME}"

#
# Build docker images immediately (needs: [], meaning it has not prerequisites)
# so longer jobs get started soon. Don't push them until the docker:push:* jobs
# below, which wait for validation (unit testing, etc)
#
# SERVICE_NAME = name of service from docker-compose.yml (key in services object)
#
docker:build:nginx:
  extends: .docker-compose-build-template
  variables:
    SERVICE_NAME: nginx

docker:build:nextjs:
  extends: .docker-compose-build-template
  variables:
    SERVICE_NAME: nextjs

#
# Push docker images after necessary jobs pass (e.g. unit testing passes)
#
docker:push:
  stage: stageless
  image: "$CI_REGISTRY/emss/docker-images:skopeo"
  variables:
    GIT_STRATEGY: none # Don't checkout the repo, just get artifacts
  tags: ["docker", "linux"]
  needs:
    - make-fit-dotenv
    - job: test
      artifacts: false
    - job: docker:build:nginx
      artifacts: false
    - job: docker:build:nextjs
      artifacts: false
  script:
    # Login to registry
    - echo $CI_JOB_TOKEN | skopeo login -u gitlab-ci-token --password-stdin $CI_REGISTRY

    # Get IMAGE_VERSION from .env
    - source .env

    - SERVICE=nginx
    - TEMP_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:preview-${IMAGE_VERSION}"
    - FINAL_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:${IMAGE_VERSION}"
    - skopeo copy "docker://${TEMP_IMAGE}" "docker://${FINAL_IMAGE}"

    - SERVICE=nextjs
    - TEMP_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:preview-${IMAGE_VERSION}"
    - FINAL_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:${IMAGE_VERSION}"
    - skopeo copy docker://$TEMP_IMAGE docker://$FINAL_IMAGE

.docker-deploy-template:
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none # Don't checkout the repo, just get artifacts
  script:
    # Ultimately it'd be good to have as much of the following wrapped up in a job template
    # that multiple projects could share. One problem may be getting the sudo password session
    # to be transferrable between before_script (in a template) and script. Then again, the docs
    # say: "Scripts you specify in before_script are concatenated with any scripts you specify
    # in the main script. The combined scripts execute together in a single shell."

    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile

    # Ultimately get this from .fitdock.yml, but need to write a method to do that
    - export INSTALL_DIR=/opt/coda

    #
    # TEMPORARY: Remove FITBox services. Don't error if services/packages no longer exist. Remove
    #            this code after it's run at least once.
    #
    - sudo systemctl stop coda || true
    - sudo systemctl stop nginx || true
    - sudo yum remove nginx nodejs *nodesource* -y || true
    #
    # ^^ TEMPORARY: Remove FITBox services
    #

    - >
      if ! sudo fitdock --version; then
        sudo git clone -b fitdock https://gitlab.fit.nasa.gov/fitbox/fitbox.git /opt/fitdock
        sudo bash /opt/fitdock/src/scripts/setup-fitdock.sh
      fi

    - >
      if [[ "${CI_COMMIT_TITLE}" =~ \[fitdock\] ]] || ! cmp --silent ./.fitdock.yml "${INSTALL_DIR}/.fitdock.yml"; then
        echo "do deploy";
        sudo mkdir -p "${INSTALL_DIR}"
        sudo chown gitlab-runner:gitlab-runner "${INSTALL_DIR}"
        /bin/cp -f ./.fitdock.yml "${INSTALL_DIR}/.fitdock.yml"
        sudo fitdock "${INSTALL_DIR}/.fitdock.yml"
      fi

    # Move into place
    # /bin/cp to avoid aliased version of `cp` which doesn't allow forcing with -f
    - /bin/cp -f ./.env "${INSTALL_DIR}/.env"
    - /bin/cp -f ./docker-compose.yml "${INSTALL_DIR}/docker-compose.yml"
    - rm -f .env
    - rm -f .fitdock.yml
    - rm -f docker-compose.yml

    # Take docker-compose down, pull latest, bring it back up
    - cd "${INSTALL_DIR}"
    - echo $CI_JOB_TOKEN | sudo /usr/bin/docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

    # Get the latest of each image
    - sudo /usr/bin/docker compose pull

    # Using the new images, re-up Compose. Also remove anything no longer defined in
    # docker-compose.yml via --remove-orphans
    - sudo /usr/bin/docker compose up -d --remove-orphans

    # remove any images no longer in use
    - sudo /usr/bin/docker image prune -af

deploy:dev1:
  extends: .docker-deploy-template
  tags: ["coda-dev1-runner"]
  needs:
    - make-fit-dotenv
    - docker:push
  environment:
    name: development1
    url: https://coda-dev.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1
  when: manual

deploy:dev2:
  extends: .docker-deploy-template
  tags: ["coda-dev2-runner"]
  needs:
    - make-fit-dotenv
    - docker:push
  environment:
    name: development2
    url: https://coda-dev2.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV2
  when: manual

deploy:int:
  extends: .docker-deploy-template
  tags: ["coda-int-runner"]
  needs:
    - make-fit-dotenv
    - docker:push
  environment:
    name: integration
    url: https://coda-int.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT
  only:
    - int

deploy:prod:
  extends: .docker-deploy-template
  tags: ["coda-prod-runner"]
  needs:
    - make-fit-dotenv
    - docker:push
    - { job: "test", artifacts: false }
    - { job: "project-check", artifacts: false }
    - { job: "phpcs-security-audit-sast", artifacts: false }
    - { job: "nodejs-scan-sast", artifacts: false }
    - { job: "semgrep-sast", artifacts: false }
    - { job: "dependency-check", artifacts: false }
  environment:
    name: production
    url: https://coda.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD
  when: manual
  only:
    - prod
