stages:
  - stageless

default:
  timeout: 10 minutes

variables:
  HOME: "/tmp" # required for openshift for now

# These includes do not define the order of the pipeline. That is determined by
# the `needs` value for each job
include:
  # Jobs that run on commits and scheduled pipelines.
  #
  # Scheduled pipelines are used to do regular reporting on things like vulnerabilities and test
  # coverage. We don't want them to build packages and Docker images or do deploys
  - local: .gitlab/run-on-schedule.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"

  # Jobs that run on commits only, not scheduled pipelines
  - local: .gitlab/run-on-commits.gitlab-ci.yml
    rules:
      - if: $CI_PIPELINE_SOURCE != "schedule"

  # Other jobs that we need for both types of pipelines
  - local: .gitlab/includes/db-import.yml
  - project: "emss/gitlab-templates"
    ref: 2.6.0
    file:
      # EMSS shared dev server helpers (carbon, iron, oxygen, etc)
      - "/jobs/emss-shared-dev.gitlab-ci.yml"
