version: "3.9"
services:
  nginx:
    container_name: coda-nginx-1
    image: ${DOCKER_IMAGE_NGINX}
    restart: unless-stopped
    depends_on:
      - apiv1
    volumes:
      - ${DOCKER_HOST_HTTP_STATIC_DIR}:/usr/share/nginx/static:ro
      - ${DOCKER_HOST_SSL_CERTS_DIR}:/etc/pki/tls/certs
      - ${DOCKER_HOST_SSL_PRIVATE_DIR}:/etc/pki/tls/private
      - .local/logs:/var/log/nginx
    ports:
      # launchpad must be over HTTPS and not have a port specified in the URL
      # e.g. https://aegis.fit.nasa.gov not https://aegis.fit.nasa.gov:8000
      - "443:443"

  apiv1:
    container_name: coda-apiv1-1
    image: ${DOCKER_IMAGE_APIV1}
    restart: unless-stopped
    env_file:
      # Any .env variables needed at runtime must be specified here or listed out in the `environment` property
      #
      # First the .env file is used to SET environment variables on the container. The .env file is
      # NOT actually moved over onto the container, just the variables are set.
      - ./.env
    environment:
      # This happens after `env_file` above. It overrides the value of CACHE_ROOT that is set in
      # .env, such that it's always /cache in the container.
      - CACHE_ROOT=/cache
    volumes:
      # Here CACHE_ROOT is whatever is specified in the .env file, because creating the volume
      # happens on the host before the container is fully running. In contrast, the `env_file` and
      # `environment` properties above happen after the container is running.
      #
      # The end result of `env_file`, `environment`, and this volume is that when using Docker,
      # the CACHE_ROOT variable in your .env file is for setting the location of the cache ONLY on
      # the host. The container's cache location is hard-coded here as `/cache`.
      - ${CACHE_ROOT}:/cache
      - ${DOCKER_HOST_HTTP_STATIC_DIR}:/static
      - .local/logs:/logs

  logstash:
    container_name: coda-logstash-1
    image: logstash:8.10.4
    # image: eegitlabregistry.fit.nasa.gov/emss-logs-logstash:dev
    command: bin/logstash -f '/etc/logstash/conf.d/logstash-{nginx}.conf'
    restart: unless-stopped
    depends_on:
      - apiv1
      - nginx
    environment:
      - MONITORING_ENABLED=false
    volumes:
      - ./docker/logstash/:/etc/logstash/conf.d
      - .local/logs:/logs
      - .local/logstash/data:/usr/share/logstash/data
