version: "3.9"
services:
  nginx:
    image: ${REGISTRY_IMAGE}/nginx:${IMAGE_VERSION}
    environment: 
      - WEB_LOGIN_PASSWORD=${WEB_LOGIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - nextjs
    volumes:
      - ./template-variables:/etc/nginx/templates/10-variables.conf.template:ro
      - ${DOCKER_HOST_HTTP_STATIC_DIR}:/usr/share/nginx/static:ro
      - ${DOCKER_HOST_SSL_CERTS_DIR}:/etc/pki/tls/certs
      - ${DOCKER_HOST_SSL_PRIVATE_DIR}:/etc/pki/tls/private
    ports:
      # AEGIS requires launchpad, so must be over HTTPS and not have a port specified in the URL
      # e.g. https://aegis.fit.nasa.gov not https://aegis.fit.nasa.gov:8000
      - "443:443"

  nextjs:
    image: ${REGISTRY_IMAGE}/nextjs:${IMAGE_VERSION}
    restart: unless-stopped
    env_file:
      # First the .env file is used to SET environment variables on the container. The .env file is
      # NOT actually moved over onto the container, just the variables are set.
      - ./.env
    environment:
      # This happens after `env_file` above. It overrides the value of CACHE_ROOT that is set in
      # .env, such that it's always /cache in the container.
      - CACHE_ROOT=/cache
    ports:
      # nextjs is hard-coded to run on 3000 in docker, and nginx proxies 3000. Hard-coding this and
      # not making it configurable keeps docker config simpler.
      - "3000:3000"

      # VS Code debug port. This isn't needed in production, and won't be exposed by FIT servers,
      # but is simpler config-wise to put here versus in the overrides file
      - "9229:9229"
    volumes:
      # Here CACHE_ROOT is whatever is specified in the .env file, because creating the volume
      # happens on the host before the container is fully running. In contrast, the `env_file` and
      # `environment` properties above happen after the container is running.
      #
      # The end result of `env_file`, `environment`, and this volume is that when using Docker,
      # the CACHE_ROOT variable in your .env file is for setting the location of the cache ONLY on
      # the host. The container's cache location is hard-coded here as `/cache`.
      - ${CACHE_ROOT}:/cache
      - ${DOCKER_HOST_HTTP_STATIC_DIR}:/static
