#
# DOCKER OVERRIDE FILE:
# This is an override file. It is intended to be used on top of the base docker-compose.yml file.
#
# SUMMARY:
# Do the exact same thing as the production `docker-compose.yml`, just build locally as a way to
# quickly preview what a production build would do.
# Don't pull an image from container registry: build it locally from a Dockerfile.
#
version: "3.9"
services:
  nginx:
    image: coda-preview-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: prod
      args:
        # Build args needed in context during build (see note in Dockerfile)
        - VITE_PUBLIC_MAPBOX_KEY=${VITE_PUBLIC_MAPBOX_KEY}
        - VITE_PUBLIC_APP_ENV=${VITE_PUBLIC_APP_ENV}
  
  apiv1:
    image: coda-preview-apiv1:latest
    build:
      context: .
      dockerfile: ./docker/apiv1/Dockerfile
      target: prod