#
# DOCKER OVERRIDE FILE:
# This is an override file. It is intended to be used on top of the base docker-compose.yml file.
#
# SUMMARY:
# Do the exact same thing as the production `docker-compose.yml`, just build locally from the Dockerfile
# instead of pulling the image from the container registry.
# Use this as a way to quickly preview what a production build would do.
#
services:
  nginx:
    image: coda-preview-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: prod
      args:
        # Build args needed in context during build (see note in Dockerfile)
        - VITE_PUBLIC_MAPBOX_KEY=${VITE_PUBLIC_MAPBOX_KEY}
        - VITE_PUBLIC_TALKYBOT_URL=${VITE_PUBLIC_TALKYBOT_URL}
        - VITE_PUBLIC_LIVE_STREAMS_ENABLED=${VITE_PUBLIC_LIVE_STREAMS_ENABLED}
        - VITE_PUBLIC_MEDIA_MTX_CONTROL_URL=${VITE_PUBLIC_MEDIA_MTX_CONTROL_URL}
        - VITE_PUBLIC_MEDIA_MTX_HLS_URL=${VITE_PUBLIC_MEDIA_MTX_HLS_URL}
        - VITE_PUBLIC_MEDIA_MTX_RECORDINGS_URL=${VITE_PUBLIC_MEDIA_MTX_RECORDINGS_URL}
        - VITE_PUBLIC_MTX_VIDEO_MAX_AGE_DAYS=${VITE_PUBLIC_MTX_VIDEO_MAX_AGE_DAYS}
        - VITE_PUBLIC_MAPLIBRE_BASE_URL=${VITE_PUBLIC_MAPLIBRE_BASE_URL}
        - VITE_PUBLIC_MAPLIBRE_PMTILES_FILENAME=${VITE_PUBLIC_MAPLIBRE_PMTILES_FILENAME}

  apiv1:
    image: coda-preview-apiv1:latest
    build:
      context: .
      dockerfile: ./docker/apiv1/Dockerfile
      target: prod
    environment:
      # Override what is in .env (which may be "localhost" to support native local dev) such
      # that it is always "database" and port 5432 in a full Docker-Compose setup.
      - DB_HOST=database
      - DB_PORT=5432
