#
# DOCKER OVERRIDE FILE:
# This is an override file. It is intended to be used on top of the base docker-compose.yml file.
#
# SUMMARY:
# 1. Rather than pull images from a container registry as done in the main docker-compose.yml,
#    instead build the images locally
# 2. Add code directory on the host machine via a volume
#
version: "3.9"
services:
  nginx:
    # In dev, don't pull an image from container registry: build it locally from a Dockerfile. Set
    # the `image` property to be something consistent and non-interference with images in the
    # container registry.
    image: coda-dev-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile

  nextjs:
    # See comment above regarding `image`/`build` overrides
    image: coda-dev-nextjs:latest
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
      target: dev
    ports:
      # nextjs is hard-coded to run on 3000 in docker, and nginx proxies 3000. Hard-coding this and
      # not making it configurable keeps docker config simpler.
      - "3000:3000"

      # VS Code debug port. This isn't needed in production, and won't be exposed by FIT servers,
      # but is simpler config-wise to put here versus in the overrides file
      - "9229:9229"
    volumes:
      # In dev we want the host's code to be present on the container
      - ./:/app

      # Create volume for node_modules that masks the node_modules directory volumed-in by the
      # `./:/app` volume. We don't want to use the host's node_modules, since it'll be constructed
      # for the host's OS. We want a node_modules set up for this container's OS.
      - ./.local/docker_node_modules:/app/node_modules
