#
# DOCKER OVERRIDE FILE:
# This is an override file. It is intended to be used on top of the base docker-compose.yml file.
#
# SUMMARY:
# Do the exact same thing as the production `docker-compose.yml`, just build locally as a way to
# quickly preview what a production build would do.
#
version: '3.9'
services:
  nginx:
    image: ${REGISTRY_IMAGE}/nginx:preview-${IMAGE_VERSION}
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile

  nextjs:
    image: ${REGISTRY_IMAGE}/nextjs:preview-${IMAGE_VERSION}
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
      target: prod
      args:
        # Build args needed in context during build (see note in Dockerfile)
        - NEXT_PUBLIC_MAPBOX_KEY=${NEXT_PUBLIC_MAPBOX_KEY}
        - NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
        - IMAGE_VERSION=${IMAGE_VERSION}
