user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    proxy_connect_timeout       28800;
    proxy_send_timeout          28800;
    proxy_read_timeout          28800;
    send_timeout                28800;

    #gzip  on;

    server {

        listen 443 ssl;
        listen [::]:443 ssl;
        server_name  maestronginx;

        ssl_certificate      /etc/pki/tls/certs/nginx.crt;
        ssl_certificate_key  /etc/pki/tls/private/nginx.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        client_max_body_size 50G;

        #
        # Serve Next.JS app
        #
        location / {
            proxy_pass http://nextjs:3000;
            proxy_redirect off;

			# Password protect nginx server
			if ($web_login_password) {
				auth_basic "Restricted";
          		auth_basic_user_file  /etc/nginx/.htpasswd;
			}

            # Not sure what the nextjs devserver needs...this good?
            proxy_buffering off;

            # This would be better not hard-coded, and instead configured via .env
            if ($http_origin ~* "^https?:\/\/(maestro(|-\w+).fit.nasa.gov(|:\d{2,5})|ares(.*?).jsc.nasa.gov(|:\d{2,5})|wiki-dev.fit.nasa.gov)$") {
                add_header 'Access-Control-Allow-Origin' "$http_origin";
                add_header 'Access-Control-Allow-Credentials' 'false' always;
                add_header 'Access-Control-Allow-Methods' 'GET' always;
            }

            # Stuff to add later
            #proxy_set_header X-Real-IP $remote_addr;
            #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for

            # For websockets
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }


        #
        # Serve static content
        #
        location /static {
            # Alias to container file system, which is a docker volume to the host system
            # defined by env var DOCKER_HOST_HTTP_PUBLIC_DIR
            alias /usr/share/nginx/static/;
            try_files $uri $uri/ =404;
        }

    }
}
