# also run standard FIT dependency and package checks
# https://gitlab.fit.nasa.gov/developer-ecosystem/ci-job-templates
include:
  - project: "developer-ecosystem/ci-job-templates"
    ref: 3.3.0
    file: "/rollups/all-projects.gitlab-ci.yml"
  - template: "Verify/Accessibility.gitlab-ci.yml"

  # Docker-in-Docker template for building docker images using docker runners
  - project: "developer-ecosystem/ci-job-templates"
    ref: 5.1.0
    file: "/extends/dind.gitlab-ci.yml"

  # Code quality checks
  - project: "emss/gitlab-templates"
    ref: main
    file: "/jobs/code-quality.gitlab-ci.yml"

stages:
  - stageless

# Override some properties on FIT jobs. Unfortunately using a template for these
# make GitLab angry, so a lot of repetition
project-check:
  stage: stageless
  needs: []
  tags: ["openshift"]
eslint-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
nodejs-scan-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
semgrep-sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
sast:
  stage: stageless
  needs: []
  tags: ["openshift"]
secret_detection:
  stage: stageless
  needs: []
  tags: ["openshift"]
code-count:
  stage: stageless
  needs: []
  tags: ["openshift"]
a11y:
  stage: stageless

# manually overwrite the dependency-check to add our own suppression.xml
dependency-check:
  stage: stageless
  needs: ["install_dependencies"] # dependency-check takes a while, don't wait for "test" job
  tags: ["docker", "linux"] # can't use openshift yet
  image:
    # Specify the Docker image to be used for the job, which is a customized image for running OWASP
    # dependency-check in a GitLab CI job
    name: $CI_REGISTRY/developer-ecosystem/dependency-check:latest
    # Entrypoint is overridden to allow a script to be run
    entrypoint: [""]
  script:
    # Run dependency-check from the location installed in the Docker container with the following arguments:
    # --scan "./"                                         Scans all files and folders within the working folder,
    #                                                     which contains the repository files as well as any
    #                                                     artifacts from prior jobs in the pipeline
    # --format ALL                                        Saves output in all formats so that HTML and JSON
    #                                                     files are available
    # --project "$CI_PROJECT_NAME"                        Use the GitLab project name, which is included in
    #                                                     the report
    # --failOnCVSS 0                                      Forces job to fail if any vulnerabilities are found
    # --suppression /suppressions/fp-cpe-suppression.xml  Suppress false positives where the dependency is
    #                                                     improperly identified
    # --suppression /suppressions/fp-cve-suppression.xml  Suppress false positives where the dependency is
    #                                                     properly identified, but the  CVE is a false positive
    - /usr/share/dependency-check/bin/dependency-check.sh --scan "./" --format ALL --project "$CI_PROJECT_NAME" --failOnCVSS 0 --suppression /suppressions/fp-cpe-suppression.xml --suppression /suppressions/fp-cve-suppression.xml --suppression ./ci/suppression.xml
  # Allow failure will report a failure, but continue execution of the pipeline
  allow_failure: true
  artifacts:
    # Saving artifacts always forces them to be saved on failure as well as success
    when: always
    # Save the HTML and JSON formatted results as artifacts
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"

npm-audit:
  stage: stageless
  image: $CI_REGISTRY/emss/docker-images/node-ci:npm-audit
  needs: []
  tags: ["openshift"]
  allow_failure: true
  script:
    # Runs `npm audit --json` then sends the results to EMSS dashboard (only on EMSS major branches)
    - >
      if
      [ "${CI_COMMIT_REF_SLUG}" == "prod" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "int" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "stable" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "beta" ] ||
      [ "${CI_COMMIT_REF_SLUG}" == "alpha" ];
      then
        node /postAuditReport.js;
      fi

    # Run this without --json to make a pretty-print for the job log, plus will pass/fail the job
    - npm audit

install_dependencies:
  stage: stageless

  # This could be openshift, but it runs faster in a VM; other jobs rely on it, so get it done ASAP
  tags: ["docker", "linux"]
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - ./node_modules/*

#
# Creates Software Bill of Materials
#
node-sbom:
  stage: stageless
  allow_failure: true
  tags: ["docker", "linux"] # Can't be openshift due to it not pulling latest tag
  needs: ["install_dependencies"]
  image: $CI_REGISTRY/emss/docker-images:node-ci-sbom
  script:
    - /create-and-compare-bom.sh ./BOM.md
  artifacts:
    when: always
    paths:
      - "./bom.json"
      - "./new-bom.md"

.make-dotenv-template:
  image: "$CI_REGISTRY/emss/docker-images:envsubst-bash-in-envsubst"
  stage: stageless
  needs: []
  tags: ["openshift"]
  before_script:
    - mkdir -p ./.local

    # Copy contents of DOTENV_SECRET from CI/CD variables to a new .env.secret file
    - echo "${DOTENV_SECRET}" > ./.env.secret

    # Determine which docker image type (dev, int, or prod) to deploy based on branch
    # Append the commit sha in order to ensure the correct build is being deployed in the case
    # multiple devs are building images simutaneously
    - >
      if [ "${CI_COMMIT_REF_SLUG}" == "prod" ]; then
          IMAGE_VERSION="prod-${CI_COMMIT_SHORT_SHA}"
      elif [ "${CI_COMMIT_REF_SLUG}" == "int" ]; then
          IMAGE_VERSION="int-${CI_COMMIT_SHORT_SHA}"
      else
          IMAGE_VERSION="dev-${CI_COMMIT_SHORT_SHA}"
      fi

    # Save image version into a an artifact to be read later in other jobs
    - echo "IMAGE_VERSION=${IMAGE_VERSION}" >> pipelineVariables.env
    # Export the variable so it can be read inside the make-dotenv.sh script
    - export IMAGE_VERSION

    # make-dotenv.sh should detect the script directory to read .env.template and write .env
    # relatively, but Alpine Linux uses standard POSIX sh, not Bash, which cannot do this [1]. So
    # we need to `cd` into the ./scripts directory first when using Alpine.
    #
    # Ref: [1] https://stackoverflow.com/a/49794678/2782380
    - cd ./scripts
  artifacts:
    reports:
      dotenv: pipelineVariables.env
    paths:
      - .env

make-dotenv:
  extends: .make-dotenv-template
  script:
    - bash ./make-dotenv.sh

make-test-dotenv:
  extends: .make-dotenv-template
  script:
    - bash ./make-dotenv.sh test

test:
  stage: stageless
  variables:
    # define variables used by Node app
    DB_HOST: postgres-test-container
    DB_PASS: test-only-password
    DB_PORT: 5432
    DB_NAME: aegis

    # plug those same variables into the Postgres container we're spinning up
    POSTGRES_PASSWORD: test-only-password
    POSTGRES_DB: aegis
  services:
    # image should match database used in docker-compose.yml
    - name: $CI_REGISTRY/emss/docker-images/postgres:postgis-14-alpine
      alias: postgres-test-container
  needs:
    - install_dependencies
    - make-test-dotenv
  tags: ["docker", "linux"]
  script:
    - npm run migrate:up
    - npm run lint
    - npm run tsc
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/cobertura-coverage.xml
      junit:
        - junit.xml
    paths:
      - ./coverage/*

# test against next version of node that CODA may use, but allow to fail
test-node-next:
  stage: stageless
  image: "$FUTURE_NODE_VERSION_IMAGE"
  needs:
    - install_dependencies
    - make-dotenv
  tags: ["openshift"]
  allow_failure: true
  script:
    - npm run lint
    - npm run tsc
    - npm t

.container-logs-template:
  when: manual
  needs: []
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
  script:
    # Start with a trivial sudo command to record the sudo password session
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile

    # OS info and partition usage
    - cat /etc/os-release
    - df -h

    # Setup artifact directories
    - LOG_ARTIFACTS=$(pwd)/log_artifacts
    - mkdir -p "${LOG_ARTIFACTS}"

    - cd /opt/coda

    # Print the last 100 lines of logs to the GitLab job log
    - sudo docker compose logs apiv1 --tail 100
    - sudo docker compose logs nginx --tail 100

    # Put the full logs into artifacts. Full logs may hit the job log length
    # limit, and generally make the job log unreadably long
    - sudo docker compose logs apiv1 > "${LOG_ARTIFACTS}/apiv1"
    - sudo docker compose logs nginx > "${LOG_ARTIFACTS}/nginx"
  artifacts:
    when: always
    paths:
      - ./log_artifacts

z-logs:dev1:
  extends: .container-logs-template
  tags: ["coda-dev1-runner"]
  needs: []
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1

z-logs:dev2:
  extends: .container-logs-template
  tags: ["coda-dev2-runner"]
  needs: []
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV2

z-logs:int:
  extends: .container-logs-template
  tags: ["coda-int-runner"]
  needs: []
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT

z-logs:prod:
  extends: .container-logs-template
  tags: ["coda-prod-runner"]
  needs: []
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD
