stages:
  - stageless

.container-logs-template:
  needs: []
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
  script:
    # Start with a trivial sudo command to record the sudo password session
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile

    # OS info and partition usage
    - cat /etc/os-release
    - df -h

    # Setup artifact directories
    - LOG_ARTIFACTS=$(pwd)/log_artifacts
    - mkdir -p "${LOG_ARTIFACTS}"

    - ps -ef
  artifacts:
    when: always
    paths:
      - ./log_artifacts

z-logs:dev1:
  extends: .container-logs-template
  tags: ["coda-dev1-runner"]
  needs: []
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1
