include:
  # Fitdock deploy template
  - project: "emss/gitlab-templates"
    ref: main
    file: "/jobs/fitdock-deploy.gitlab-ci.yml"

  # Kaniko build template
  - project: "emss/gitlab-templates"
    ref: main
    file: "/jobs/kaniko-build.gitlab-ci.yml"

.kaniko-build-template:
  extends: .emss-kaniko-build # use job template from gitlab-templates repo
  stage: stageless
  needs:
    - make-dotenv
  before_script:
    # required for containers to have NASA CA cert
    - echo "${ENV_LOCAL_CERT_PEM}" > ./.env.local.cert.pem

#
# Build docker images immediately
# SERVICE_NAME = name of service from docker-compose.yml (key in services object)
#
docker:build:nginx:
  extends: .kaniko-build-template
  variables:
    SERVICE_NAME: nginx
    MULTISTAGE_TARGET: prod
    NGINX_BASE_IMAGE: eegitlabregistry.fit.nasa.gov/emss/docker-images/nginx:1.23.0-alpine
    NODE_BASE_IMAGE: $CURRENT_NODE_VERSION_IMAGE
    MAP_ENV_VARS_TO_BUILD_ARGS: |
      NGINX_BASE_IMAGE
      NODE_BASE_IMAGE
      VITE_PUBLIC_MAPBOX_KEY
      VITE_PUBLIC_APP_ENV

docker:build:apiv1:
  extends: .kaniko-build-template
  variables:
    SERVICE_NAME: apiv1
    MULTISTAGE_TARGET: prod
    APIV1_BASE_IMAGE: $CURRENT_NODE_VERSION_IMAGE
    MAP_ENV_VARS_TO_BUILD_ARGS: |
      APIV1_BASE_IMAGE

#
# Retag docker images after necessary jobs pass (e.g. unit testing passes)
#
docker:retag:
  stage: stageless
  image: "$CI_REGISTRY/emss/docker-images:skopeo"
  variables:
    GIT_STRATEGY: none # Don't checkout the repo, just get artifacts
  tags: ["docker", "linux"]
  needs:
    - make-dotenv
    - job: test
      artifacts: false
    - job: docker:build:nginx
      artifacts: false
    - job: docker:build:apiv1
      artifacts: false
  script:
    # Login to registry
    - echo $CI_JOB_TOKEN | skopeo login -u gitlab-ci-token --password-stdin $CI_REGISTRY

    # Get the same value as IMAGE_VERSION var in .env, but without having to parse .env.
    # See make-dotenv job/template.
    - set -o allexport && source ./.env && set +o allexport

    - SERVICE=nginx
    - TEMP_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:preview-${IMAGE_VERSION}"
    - FINAL_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:${IMAGE_VERSION}"
    - skopeo copy "docker://${TEMP_IMAGE}" "docker://${FINAL_IMAGE}"

    - SERVICE=apiv1
    - TEMP_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:preview-${IMAGE_VERSION}"
    - FINAL_IMAGE="${CI_REGISTRY_IMAGE}/${SERVICE}:${IMAGE_VERSION}"
    - skopeo copy docker://$TEMP_IMAGE docker://$FINAL_IMAGE

deploy:artifactize-committed-files:
  image: "$CI_REGISTRY/emss/docker-images:envsubst-bash-in-envsubst"
  stage: stageless
  needs: []
  tags: ["openshift"]
  script:
    - echo "This job runs no commands, just turns .fitdock.yml and docker-compose.yml into artifacts"
  artifacts:
    paths:
      - .fitdock.yml
      - docker-compose.yml

.docker-deploy-template:
  extends: .emss-fitdock-deploy # use job template from gitlab-templates repo

deploy:dev1:
  extends: .docker-deploy-template
  tags: ["coda-dev1-runner"]
  needs:
    - make-dotenv
    - docker:retag
    - deploy:artifactize-committed-files
  environment:
    name: development1
    url: https://coda-dev.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1
  when: manual
  before_script:
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile

      # Since this runner is shared between all EMSS repos, we need to check if any containers that
    # are running are this app or something else. Ultimately this code needs to be in the EMSS
    # deploy template, and needs to do the `grep -q "/opt/coda"` part in an app-agnostic way (e.g.
    # needs to grab the INSTALL_PATH from .fitdock.yml), but for now this is hard-coded for CODA.
    # If-statement below does two checks:
    # 1. If `sudo docker compose ls` lists more than 2 lines, this means there are more than two
    #    docker-compose apps running (first line is just the header). Here's an example of AEGIS
    #    and Labs running simultaneously:
    #       ejmontal@jsfitdaegis01 / $ sudo docker compose ls
    #       NAME                STATUS              CONFIG FILES
    #       aegis               running(3)          /opt/aegis/docker-compose.yml
    #       emss-labs           running(5)          /opt/emss-labs/docker-compose.yml
    #    If this is the case, we definitely are in a weird condition and want to nuke all containers
    #    and let this deploy job bring us back to a normal configuration.
    # 2. If `sudo docker compose ls` does NOT included this app's install directory (/opt/aegis),
    #    then some other app was the most recently deployed app. Nuke all containers and let this
    #    deploy job make AEGIS the running app.
    # - COMPOSE_LS=$(sudo docker compose ls)
    # - >
    #   if [ $(echo "$COMPOSE_LS" | wc -l) -gt 2 ] || ! echo "$COMPOSE_LS" | grep -q "/opt/coda"; then
    #     echo "Unknown docker-compose apps running, killing all containers."
    #     sudo docker stop $(sudo docker ps -a -q)
    #   else
    #     echo "Same app deploying, not killing containers"
    #   fi

# CODA-Dev2 currently functioning as Talky Bot prod
# deploy:dev2:
#   extends: .docker-deploy-template
#   tags: ["coda-dev2-runner"]
#   needs:
#     - make-dotenv
#     - docker:retag
#     - deploy:artifactize-committed-files
#   environment:
#     name: development2
#     url: https://coda-dev2.fit.nasa.gov
#   variables:
#     DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV2
#   when: manual

deploy:int:
  extends: .docker-deploy-template
  tags: ["coda-int-runner"]
  needs:
    - make-dotenv
    - docker:retag
    - deploy:artifactize-committed-files
  environment:
    name: integration
    url: https://coda-int.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT
  only:
    - int

deploy:prod:
  extends: .docker-deploy-template
  tags: ["coda-prod-runner"]
  needs:
    - make-dotenv
    - docker:retag
    - deploy:artifactize-committed-files
    - { job: "test", artifacts: false }
    - { job: "project-check", artifacts: false }
    # - { job: "phpcs-security-audit-sast", artifacts: false }
    # - { job: "nodejs-scan-sast", artifacts: false }
    - { job: "semgrep-sast", artifacts: false }
    - { job: "dependency-check", artifacts: false }
  environment:
    name: production
    url: https://coda.fit.nasa.gov
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD
  when: manual
  only:
    - prod

.db-export-template:
  needs: []
  # I don't think we want to do this, because I don't think we want GitLab to consider this a
  # deployment. It's just grabbing some data off of Production.
  # environment:
  #   name: production
  #   url: https://coda.fit.nasa.gov
  when: manual
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
  script:
    # init sudo ability
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile
    - PROJECT_DIR=$(pwd)
    - cd /opt/coda
    - sudo docker compose exec database pg_dump -U postgres coda > "${PROJECT_DIR}/coda.sql"
  artifacts:
    paths:
      - coda.sql

z:db-export:prod:
  extends: .db-export-template
  # when: always
  tags: ["coda-prod-runner"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_PROD #CI/CD Variable

z:db-export:int:
  extends: .db-export-template
  tags: ["coda-int-runner"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT #CI/CD Variable

z:db-export:dev1:
  extends: .db-export-template
  tags: ["coda-dev1-runner"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1 #CI/CD Variable

z:db-export:dev2:
  extends: .db-export-template
  tags: ["coda-dev2-runner"]
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV2 #CI/CD Variable

.db-import-template:
  when: manual
  stage: stageless
  timeout: 10 minutes
  variables:
    GIT_STRATEGY: none
  script:
    # init sudo ability
    - echo "${DEPLOY_SUDO_PASS}" | sudo -S touch /tmp/somefile
    - PROJECT_DIR=$(pwd)
    - cd /opt/coda
    - cp "${PROJECT_DIR}/coda.sql" /d1/coda/db-init/coda.sql

    # Stop docker compose, then remove database files
    - sudo /usr/bin/docker compose down --remove-orphans
    - sudo rm -rf /d1/coda/postgres

    # Bring docker compose back up, which will use the file at /d1/coda/db-init/coda.sql, then remove it
    - sudo /usr/bin/docker compose up -d
    - sudo rm -f /d1/coda/db-init/coda.sql

    # Migrations will be run when the apiv1 container restarts

z:db-import:dev1:
  extends: .db-import-template
  tags: ["coda-dev1-runner"]
  needs: ["z:db-export:prod"]
  environment:
    name: development1
    url: $URL
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_DEV1 #CI/CD Variable
    URL: https://coda-dev1.fit.nasa.gov

z:db-import:int:
  extends: .db-import-template
  tags: ["coda-int-runner"]
  needs: ["z:db-export:prod"]
  environment:
    name: integration
    url: $URL
  variables:
    DEPLOY_SUDO_PASS: $DEPLOY_SUDO_PASS_INT #CI/CD Variable
    URL: https://coda-int.fit.nasa.gov
