#!/usr/bin/env bash
#
#


# Your username created by a wiki.jsc.nasa.gov admin
USERNAME="Yourusername"

# Your password, generated by a wiki.jsc.nasa.gov admin
USERPASS="A_secure_password"

# API to access. Note the for the EVA Wiki this will include "eva", whereas
# for the FOD Wiki it will include "fod"
WIKIAPI="https://wiki.jsc.nasa.gov/eva/api.php"

# Path to your CA Cert obained from [1] and located at in $CA_CERT below.
# If not specified, the system's default CA cert will be used, which may not
# include NASA internal certificates.
#
# Refs:
#  [1] https://etads.nasa.gov/idi/ntam/
# CA_CERT="/path/to/alternate/cacert.pem"
