input {
  file {
    path => "/logs/nginx_access.log"
    start_position => "beginning"
    tags => [ "coda-nginx" ]
  }
}

filter {
  grok {
   match => [ "message" , '%{IPORHOST:clientip} - \[%{HTTPDATE:timestamp}\] \"(?:%{WORD:method} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-) (?:%{NUMBER:requesttime}|-) (?:%{NUMBER:upstreamresponsetime}|-) (?:%{NUMBER:msec}|-) (?:%{NOTSPACE:upstreamaddr}|-) \"%{NOTSPACE:referrer}\" \"%{GREEDYDATA:agent}\"']
   overwrite => [ "message" ]
  }
  date {
    match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
    remove_field => [ "timestamp" ]
  }
}


output {
  http {
    url => 'https://maestro-alpha.fit.nasa.gov/logstash/'
    http_method => post
    retry_non_idempotent => true
    format => json_batch
    http_compression => true
  }
  stdout { codec => rubydebug }
}
