import { faTrashAlt } from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { FunctionComponent, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router";
import { getCurrentUser } from "packages/getCurrentUser";
import { isSuperuser } from "utils/user";
import adminCommon from "./adminCommon.module.css";

const AdminPcdAudio: FunctionComponent = () => {
  const navigate = useNavigate();
  const [records, setRecords] = useState<PcdAudioListItem[]>([]);

  useEffect(() => {
    (async () => {
      const user = await getCurrentUser();
      if (user instanceof Error || !isSuperuser(user)) {
        navigate("/");
        return;
      }
      const response = await fetch(`/api/v1/db/pcdAudio`);
      const data: PcdAudioListItem[] = await response.json();
      setRecords(data);
    })();
  }, [navigate]);

  const handleDelete = async (id: number) => {
    if (!confirm("Are you sure you want to delete this PCD audio record?")) return;
    await fetch(`/api/v1/db/pcdAudio/${id}`, { method: "DELETE" });
    setRecords(records.filter((r) => r.id !== id));
  };

  return (
    <main className={adminCommon.page}>
      <div className={adminCommon.container}>
        <Link to="/admin" className={adminCommon.backLink}>
          ← Admin
        </Link>
        <h1 className={adminCommon.pageTitle}>PCD Audio</h1>
        <p className={adminCommon.introText}>
          Crew PCD (Personal Crew Device) audio recordings fetched from Imagery Online. Generated by{" "}
          <code>src/server/processing/artemis2/pcd_audio/fetch-audio-metadata.mjs</code> and stored
          here as the full JSON output keyed by source.
        </p>

        <section className={adminCommon.section}>
          <h2 className={adminCommon.sectionHeading}>Records</h2>
          <div className={adminCommon.details}>
            <Link to="/admin/pcdAudioUpsert" className={adminCommon.createButton}>
              + Add PCD Audio
            </Link>

            {records.length === 0 ? (
              <p className={adminCommon.emptyState}>No PCD audio records found.</p>
            ) : (
              <ul className={adminCommon.dateGroupRecords} style={{ marginTop: "12px" }}>
                {records.map((record) => (
                  <li key={record.id} className={adminCommon.recordItem}>
                    <Link
                      to={`/admin/pcdAudioUpsert?id=${record.id}`}
                      className={adminCommon.recordLink}
                    >
                      {record.source}
                      <span className={adminCommon.recordMeta}>
                        {" "}
                        — {record.recordingCount} recording{record.recordingCount === 1 ? "" : "s"}
                        {record.dateStart && record.dateEnd
                          ? ` · ${record.dateStart} → ${record.dateEnd}`
                          : ""}
                        {" · generated "}
                        {record.generatedAt ? new Date(record.generatedAt).toLocaleString() : "—"}
                        {record.notes ? ` · ${record.notes}` : ""}
                      </span>
                    </Link>
                    <button
                      type="button"
                      className={adminCommon.deleteButton}
                      onClick={() => handleDelete(record.id)}
                      aria-label={`Delete PCD audio record for ${record.source}`}
                    >
                      <FontAwesomeIcon icon={faTrashAlt} />
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </section>
      </div>
    </main>
  );
};

export default AdminPcdAudio;
